### ISSUE TITLE
changes to data not being reflected

### ISSUE THREAD

**Issue by gabrielflorit** [maxogden/dat#127]
I'm unable to see new data versions.

Here's **crime.csv**:
```
ID,CRIME
1,theft
2,assault
```

I run:
````
cat crimes.csv | dat import --csv --primary=ID
dat cat
```

Which returns:

``` json
{"key":"1","version":1,"ID":"1","CRIME":"theft"}
{"key":"2","version":1,"ID":"2","CRIME":"assault"}
```

I then modify the second row in **crime.csv**:
```
ID,CRIME
1,theft
2,murder
```

and run:
````
cat crimes.csv | dat import --csv --primary=ID
dat cat
```

Which doesn't return the new data:
``` json
{"key":"1","version":1,"ID":"1","CRIME":"theft"}
{"key":"2","version":1,"ID":"2","CRIME":"assault"}
```

What am I doing wrong?

**Comment by karissa** [comment]
Hey @gabrielflorit and co:

We've now merged dat beta, and since this refers to the alpha version I think we're going to close this thread. The OP bug in question should be fixed now.

@paulfitz: we are now supporting 2-way merges, so for a three-way merge you'd want to perform 2 separate merge operations right now.

@museums-io: the default behavior now overrides keys if you import using ```--key=<same-key>```. We are embracing forks and rollbacks now, so if two different changes diverge, you can always still go back in time and hop around the graph. How could dat work with your system now? Are interested in trying out the new version and reporting bugs?

See the following docs for more info on the new beta merge:
[http://dat-data.com](website intro)
[https://github.com/maxogden/dat/blob/master/docs/cli-docs.md](cli api)
[https://github.com/maxogden/dat/blob/master/docs/whitepaper.md[(whitepaper)

Thanks for

**Comment by gabrielflorit** [comment]
Thank you so much @karissa !
