### ISSUE TITLE
Changes not pushed to other instance of dat

### ISSUE THREAD

**Issue by kayakr** [maxogden/dat#156]
Having set up two dat instances (alice, bob) on :6461 and :6462 respectively, making an edit via dat-editor ups the version for the row, but no changes are pushed to the second instance.

```BASH
22:34:56 jonathan:~/Documents/HuntDesign/Projects/dat-test/alice (master) $ dat cat
{"date":"2014-06-02","temperature":62.5,"key":"chz2hymhn0000btx4mp5567z9","version":1}
{"date":"2014-06-03","temperature":"64.3","key":"chz2hyn7s0000bvx473mqbvno","version":3}

22:36:23 jonathan:~/Documents/HuntDesign/Projects/dat-test/alice (master) $ dat listen
Listening on port 6461
```

// Edit data value via dat-editor

```BASH
^C22:37:07 jonathan:~/Documents/HuntDesign/Projects/dat-test/alice (master) $ dat cat
{"date":"2014-06-02","temperature":62.5,"key":"chz2hymhn0000btx4mp5567z9","version":1}
{"date":"2014-06-03","temperature":"64.4","key":"chz2hyn7s0000bvx473mqbvno","version":4}
22:37:11 jonathan:~/Documents/HuntDesign/Projects/dat-test/alice (master) $ dat push http://localhost:6462
Elapsed      : 0 s
Pushed       : 0 B       (0 B/s)
 - changes : 0
 - blobs   : 0

Push to remote has completed.
```

**Comment by karissa** [comment]
Hey all,

I'm going to close this issue because it refers to the alpha version. We rewrote some key parts in dat, including the underlying replication mechanism and graph.  We just merged the new Beta version of Dat, so if you reinstall dat using `npm uninstall dat && npm install -g dat` you should get the new version. Want to play around with it and see where you get?

Here is the command line documentation:
https://github.com/maxogden/dat/blob/master/docs/cli-docs.md

I wrote a first draft of a paper that might be helpful in explaining how the dat beta works: 
https://github.com/maxogden/dat/blob/master/docs/whitepaper.md

Woot!
