### ISSUE TITLE
dat init should create a readme.md if it does not exist

### ISSUE THREAD

**Issue by maxogden** [maxogden/dat#244]
potentially with some template text, or just maybe copy the description into the readme. the idea is to encourage people to document their datasets

**Comment by thadguidry** [comment]
I think even more than this...there should be an identifiers.md  (maybe just a metadata.md or properties.md)

because a dataset can be equated to a number of identifiers and the global work for such is coming up in a few months from governments and scientific institutions - this just happened in October 2014 and is a REALLY BIG DEAL - http://www.copdess.org/home/statement-of-commitment/

Among other things for data needs, they mention a commitment to: 
"Promote and implement links to data sets in publications and corresponding links to journals in data facilities via persistent identifiers. Data sets should ideally be referenced using registered DOI’s.
Promote use of other relevant community permanent identifiers for samples (IGSN), researchers (ORCID), and funders and grants (FundRef)."

So having an identifiers.md file that can contain a list of the dataset's known identifiers will be needed and queryable.

ORCID:zz2233891
subject:Geology
subject:Earthquake
subject:Alaska
subject:Aleutian Islands
FundRef:fr99991234

It will also be needed for the global dat repostiory search feature.  Find me the dataset with ORCID::zz2233891

**Comment by slang800** [comment]
I feel like creating a `README.md` when you initialize dat makes a lot of assumptions about the project. Like:
- the project is using markdown, rather than LaTeX or reStructuredText or Textile
- the project is actually going to be maintained, rather than just being a test to try out dat or a quick place to dump some data before exporting it to somewhere else.
- the dat project is being used by a human, rather than being created by a script which may have no knowledge of the name/description or no use for a readme.

It would be much better if creating a readme was done by a separate tool that wraps dat... like how `git init` doesn't ask for any information and remains extremely minimal, while GitHub does ask for a name/description and can create a readme/gitignore/license for you.

**Comment by ngoldman** [comment]
@slang800++
Though I prefer a `README.md`, I don't think that's appropriate to `dat`'s role in a workflow. `git init` wouldn't do that, nor would `npm init`. `readme init` might though.

**Comment by karissa** [comment]
I agree with the sentiments here. Cool with closing this @maxogden ?
