### ISSUE TITLE
Version Update Mechanism

### ISSUE THREAD

**Issue by john-m-howard** [maxogden/dat#281]
First, thank you for working on such a great tool.  May researchers here at NIST are interested in this type of application.  

Strangely enough I am having a hard time determining the command line functionality for updating the version of data.  The documentation is a bit unclear on this point.

Do I import it again?  This just seems to cat the second import on to the end of the first.  

Pushing the data to the remote host seems to do nothing regardless of whether or not I do "dat listen" or "dat serve"  These commands seem close in their usage, could you possibly differentiate their usage, either in your response to this issue, or in DAT documentation.

**Comment by maxogden** [comment]
@john-m-howard Hi there, thanks for trying out Dat.

The behavior in the alpha version (whats currently out now) is that if you were to import a CSV like this:

```
a,b,c
1,2,3
```

then dat would add `key` and `version` fields automatically (if they were not present in the data you imported), so for example this is what would be stored in dat:

```
key,version,a,b,c                                                                         
ci6iep8wk00001dq7js1lxf2i,1,1,2,3
```

`ci6iep8wk00001dq7js1lxf2i` is a UUID that dat generated (since there was no `key` field in the data, and a `primary` option was not set during the import)

So as you can see, the `key` and `version` fields are only 2 mandatory fields for data in dat, and they will  be generated if they are not supplied.

To answer your question, to update data in the Alpha version you have to supply the `key` and `version` fields in order to update data for each row. If your source dataset has a unique key that you can use, you can specify that at import time. Another option would be to export the data out of dat using `dat cat --csv`, modify that CSV and then import it again and it will update changed rows only.

We are currently working on implementation of the Beta version of Dat which will simplify the import/update process quite a bit.

Can you tell me more about the use cases you have in mind? We could set up a Google Hangout possibly as well if that is easier for discussion purposes.

**Comment by john-m-howard** [comment]
Max,

Thank you so much for your quick reply.  I haven't had a chance yet to try out what you said unfortunately, but I will as soon as possible (likely tomorrow).  In terms of use cases we want to move our dataset distribution infrastructure entirely online, and given that much of our data comes from human sources, a small amount of the data is often updated over time as corruption is identified.  We use GIT for our code base, and would like many of the features to use on our data.  Since we distribute our data to teams of researchers with their own code bases, your idea of eliminating one off code for reformatting dataset is also very appealing.

I'll touch base again after trying out the functionality you outlined.  A hangout may be best.

Thanks,

John

**Comment by karissa** [comment]
Hey @john-m-howard ,

We just merged the new Beta version of Dat, so if you reinstall dat using `npm uninstall dat && npm install -g dat` you should get the new version.

I wrote a first draft of a paper that might be helpful in explaining how dat works. 

Here are the command line documentation:
https://github.com/maxogden/dat/blob/master/docs/cli-docs.md

**Comment by karissa** [comment]
@john-m-howard -- PS.

Are you using a public github repository right now to publish/collaborate with your data? Let us know if you find any bugs or if anything seems confusing -- its possible that some of this stuff is a little rough around the edges because it is so new.

I'd also be happy to get on a google hangout sometime.

Best,
Karissa

**Comment by karissa** [comment]
Thanks for trying out dat beta and submitting an issue. After a whole year of feedback from the community, we recently published a new version of dat... and it makes this issue obsolete. Would you mind trying out the new dat with `npm install -g dat`? You can read about the new dat [announcement on the website](http://dat-data.com/blog/2016-02-01-dat-1) and [how it works in the docs](https://github.com/datproject/docs/blob/master/how-dat-works.md).
