### ISSUE TITLE
Indexing data in an external service

### ISSUE THREAD

**Issue by hubgit** [maxogden/dat#303]
I'd like to be able to query data that's currently stored in dat (e.g. filtering rows by values in a column other than the key). 

As providing a full query interface is outside the scope of dat, this involves copying the data into another service (e.g. elasticsearch, or a key-value store that uses a different field as the key).

What would be the simplest way to do this and keep the external index up-to-date with changes in dat?

Is it possible to write a plugin that can push data to an external service when it's updated in dat (this would be easiest), or would the external service have to subscribe to the changes feed?

**Comment by ekg** [comment]
I actually hope that full query support is in the scope of dat. Would it be
too difficult to index every column in every row?

**Comment by hubgit** [comment]
[dat-elasticsearch-upload](https://github.com/astro/dat-elasticsearch-upload) is probably relevant.

**Comment by thadguidry** [comment]
@hubgit  @ekg You don't really need to COPY the data... you could just write a nice backend layer for dat.  Remember that dat is more like middleware and the backend storage can be swapped out with anything actually.  So the backend could actually be ElasticSearch itself, its just that someone needs to do the backend storage setups or the work on that.

I would suggest that you re-read the small-core philosophy around dat and where it fits in with its original problem space.  (dat does not have to provide everything)

**Comment by hubgit** [comment]
Looking at [the list of LevelDOWN-compatible storage back-ends](https://github.com/rvagg/node-levelup/wiki/Modules#storage), I can see [a MongoDB back-end](https://github.com/rvagg/node-levelup/wiki/Modules#storage) that could be useful (especially if it'll work with a MongoDB instance hosted elsewhere).

**Comment by ekg** [comment]
@thadguidry I'm not necessarily suggesting that dat core contain this interface, although there might be reasons to support it.

I'd like to log transformations of data in dat within dat itself. This starts to seem very hard to do if I can't explain the subset of the data I'm working on in a way that dat can understand. If querying the data needs to be outside of the core, then I can only tell dat when I've updated something by showing it the old thing and new thing. I can't simply tell dat what I _would_ do to update the data set, because there is no obvious way to specify the range over which the function has to be executed in a backend-agnostic way. Does this make sense?

I'm curious what @mafintosh thinks.

**Comment by karissa** [comment]
There might be something related in https://github.com/maxogden/npm-readme-search, using dat to update a sqllite search index. It might be incompatible now that dat has upgraded to beta, though.

**Comment by karissa** [comment]
this is related to #361 and #318

**Comment by karissa** [comment]
After a whole year of feedback from the community, we recently published a new version of dat. Would you mind trying out the new dat with `npm install -g dat`? You can read about the new dat [announcement on the website](http://dat-data.com/blog/2016-02-01-dat-1) and [how it works in the docs](https://github.com/datproject/docs/blob/master/how-dat-works.md). 

This issue might be best related to an external module now that I started working on: http://github.com/karissa/dat-manager
