### ISSUE TITLE
Storage "frontends"

### ISSUE THREAD

**Issue by vespakoen** [maxogden/dat#361]
Hey there!

For my company I need to store data in Elasticsearch, PostgreSQL (+PostGIS) and LevelDB.
To facilitate storing something into multiple backends I wrote "[dstore](https://github.com/trappsnl/dstore)" (docs are outdated, but should give you a rough idea of what it does).

I have been wresting with the same problems as you have, I have learned a lot of a do's and don'ts and I am considering bringing new efforts into dat instead of dstore.

## goal

Provide a way to easily sync (and keep in sync) data into a variety of databases.

## requirements

For this to work we need a couple of things:

1) A "uniform" format for types.

So we can easily translate a "dat type" to the corresponding type of a database.
e.g. a `point` becomes a `GEOMETRY(Point, 4326)` in PostgreSQL + PostGIS and becomes a `geo_point` field in Elasticsearch.

2) A "uniform" format for different types of data.

for example:
- geo data is represented as GeoJSON
- dates are in ISO8601

3) A way to tell dat what the schema looks like for a dataset.

Something like:
```json
{
  "id": {
    "type": "uuid",
    "primary": true
  },
  "pin": {
    "type": "point",
    "elasticsearch": {
      "precision_step": 14
    }
  }
}
```

5) Serializers that accept dat data and serialize it into a valid input stream for different databases / indexes.

4) A way to tell dat where datasets should be synced to.

## questions

1) Is this something you consider adding to the core?

2) Is there already work being done for achieving something similar?

Thanks!

**Comment by maxogden** [comment]
@vespakoen Hey, thanks for the awesome issue.

We have talked about very similar functionality but got as far as you. In the past I have referred to it in our discussions as 'table sync' and 'schema mapping', the ideas are pretty much the same though.

I think it would be super useful for people exposing 'legacy' datasets using dat (e.g. having to write code that continuously imports from a data source and dumps it in a dat so that people can simply 'dat pull', basically using dat as a proxy to turn a non-syncing dataset into a syncing one.

Another use case would be if you forked someone elses dat, and maintained a 'live fork' that continuously was syncing the upstream data, transforming the schemas, and writing the updated version into the local dat (or you could also transform them on the way out). An example of this might be if I wanted to combine multiple disparate datasets maintained by different authors in different schemas and combine them and re-host them as a unified, merged custom schema.

Over a year ago now, much earlier on in the project, we prototyped this tool out: https://www.npmjs.com/package/transformer

The idea was to build a graph of compatible input/output transformations and then eventually a sort of 'solver' that could figure out how to get (if possible) from format A to B by routing the data through the appropriate transformations. But I think this was too early and too ambitious, we should start with something simpler I think and build up from there.

The format we've been using for serialization is Protocol Buffers, it's very flexible and you can configure your Dat to use protobuf as the encoding (rather than the default JSON). I think it would be interesting to work on something simple that could map to and from protobuf using a syntax like what you specced out above.

We would definitely have to add some 'hooks' into dat so that you could integrate in the schema mapping steps into the dat workflow.

I think if we could make something kinda along the lines of https://github.com/maxogden/abstract-blob-store, https://github.com/Level/abstract-leveldown or https://github.com/diasdavid/abstract-stream-muxer but for schema mapping it could be nice, because then developers could write an e.g. 'postgres-schema-mapper' and publish it to npm, then someone can use that when hooking up their postgres database to dat to sync to something else. We try to focus on enabling ecosystems rather than building huge projects with support for everything under the sun inside a `lib/` folder.

Ok, sorry for the braindump. You should definitely keep hanging in our IRC and we can continue to brainstorm stuff.

**Comment by thadguidry** [comment]
Part of this complexity is dealt with other types of OpenSource software in
the realm of ETL (Extract, Transform, Load)
There are a few OpenSource ETL tools out there with a slight learning curve
that you could also use to do your syncing.  My tool of choice is Pentaho
PDI.

Thad
+ThadGuidry <https://www.google.com/+ThadGuidry>

**Comment by vespakoen** [comment]
Cool! I am happy that there is common ground.

I also started with too big of a vision for dstore, and then later split it up into smaller pieces.
Now I was actually in the process of turning everything into "one big stream", which reminded me of dat (I had seen it before) and really gave the project a good look.
Then I realized that it makes much more sense to integrate something into dat, or make something that works with it.

Here's my brainfart:

I think we need a way to open up a stream on dat that accepts "changes".

I am not sure how changes are formatted right now, but ideally, I should be able to hack up a node script that listens to some feed, and when it get's a change, formats it into the format that dat will except and spit it out, something like this:

**thingThatSpitsOutChangesForever.js**
```js
someSourceStream.pipe(through(function (data) {
  if (data.somethingThatIndicatesItWasAPut) {
    this.emit('data', {"type": "put", "item": data.fieldThatContainsAllTheCoolData});
  } else if (data.somethingThatIndicatesItWasADel) {
    this.emit('data', {"type": "del", "id": data.idField});
  }
}))
.pipe(datify) // protobuf I guess?
.pipe(process.stdout);
```

Importing "live" data:
```shell
node thingThatSpitsOutChangesForever.js | dat stream --import
```

For exporting "live", it would probably be nice if we could limit the query (--lt(e) --gt(e)) and be able to tell it from what version it should start streaming stuff.

1) Stream out everything that is in the dataset, and keep on streaming new changes after that.
```shell
psql -c "DROP DATABASE test;"
dat stream --export | node thingThatPublishesDataToPG.js
```

2) Only stream changes that happened after a certain version
```shell
dat stream --export --from=4191882d3934588dd23a86a66afc7a329cba58182799bc4151d701309a520b6e | node thingThatPublishesDataToPG.js
```

Excuse me for the wrong terminology, I haven't used dat yet and need to explore it some more ;)

Let me know what you think!

@thadguidry Thanks for introducing me to the word "ETL", I didn't know it existed and opened up a new world for me.

**Comment by karissa** [comment]
Hey @vespakoen, everything in dat is streaming from the ground up (yay!) so I really think that your suggestions will work.

`dat import - -d <dataset-name> -f <format>` will take a stream import in a given format (tsv, csv, ndjson supported). We could add a format type, `changes` or something, so it would be as simple as

`node thingThatSpitsOutChangesForever.js | dat import - -d mydataset -f changes`

 On exporting changes, we already have `createChangesStream` in dat-core https://github.com/maxogden/dat-core/blob/master/index.js#L626, so it'd be a matter of creating a `dat changes` cli command that could stay open forever

**Comment by vespakoen** [comment]
I like the "changes" format idea!

I think providing these options will come a long way, more advanced / sophisticated options can easily be added later.

For now, I started working on "schema-mapper" (shamelessly copied from @maxogden :smile:)
Which I try to keep as simple and modular as possible, if anyone wants to help out over there, let me know and I'll add you as a collaborator.

Let's see where this end up =)

**Comment by karissa** [comment]
@mafintosh in order to do this modularly, can we have a function in dat-core that exposes the stream of individual changes, not commits (live, similar to changesdown maybe?)

**Comment by vespakoen** [comment]
Hey, I see that you have worked on implementing the changes options, cool!
I also see dat has taken a different direction which I can respect.

I am guessing this issue has become obsolete, and perhaps can be closed?

Lastly, I finally (created a website for myself and) put up a description of the schema-mapper project over here: http://koenschmeets.nl/projects/schema-mapper/

Would love some feedback from you guys!

I would love to get some feedback on it =)

**Comment by karissa** [comment]
Yeah, you're right, it can be closed. After a whole year of feedback from the community, we recently published a new version of dat. Would you mind trying out the new dat with `npm install -g dat`? You can read about the new dat [announcement on the website](http://dat-data.com/blog/2016-02-01-dat-1) and [how it works in the docs](https://github.com/datproject/docs/blob/master/how-dat-works.md).
