### ISSUE TITLE
compound keys

### ISSUE THREAD

**Issue by karissa** [maxogden/dat#372]
I hear that compound keys are desired (on import)

```
dat import -d dataset /path/to/file.csv --key=city,state,zip
```

Concatenated using a separator, and sorted internally in case they're given in scrambled order

cc @talos

**Comment by talos** [comment]
:+1: 

What do you mean by "scrambled order"?

**Comment by karissa** [comment]
@talos city,state,zip should be the same as zip,city,state

**Comment by talos** [comment]
Got it.  For the sake of uniqueness it doesn't matter, but I guess I don't see the advantage of overriding what could be the user's choice in order.  Certainly for primary keys in MySQL or Postgres, the order of a compound key could be chosen so that it could aid in joins.  While this might not matter now for dat, in the future perhaps it could, and this behavior could be problematic.

Your choice -- just glad to see this on the roadmap!

**Comment by karissa** [comment]
Ah good point. Perhaps we should make it auto order now for simplicity's
sake and add an option later to force the given order

On Tuesday, August 4, 2015, john krauss <notifications@github.com> wrote:

> Got it. For the sake of uniqueness it doesn't matter, but I guess I don't
> see the advantage of overriding what could be the user's choice in order.
> Certainly for primary keys in MySQL or Postgres, the order of a compound
> key could be chosen so that it could aid in joins. While this might not
> matter now for dat, in the future perhaps it could, and this behavior could
> be problematic.
>
> Your choice -- just glad to see this on the roadmap!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maxogden/dat/issues/372#issuecomment-127812790>.
>


-- 
Karissa McKelvey
http://karissa.github.io/ <http://karissamck.com>

Send me an encrypted message:
https://keybase.io/karissa <https://keybase.io/karissa/key.asc>

**Comment by talos** [comment]
Awesome, thanks.  I'll take this feature for a spin with some civic datasets next week.
