### ISSUE TITLE
Keys aren't deleted when rows are deleted from files

### ISSUE THREAD

**Issue by sorrell** [maxogden/dat#381]
After deleting rows from a file and importing via dat, dat doesn't recognize deleted rows.

Steps to reproduce:  
  1.  Import file with numeric key
  2.  Delete row or change row key value
  3.  Import file again with numeric key
  4.  No changes detected on deletion, new row detected on change

See video: http://npsorrell.com/dump/Bug.mp4

**Comment by karissa** [comment]
Ahh, right. Good point. I think this is the expected behavior as in each import is treated as an update command.

Perhaps 'import' should imply that the new file is whole, and something like `update` would expect rows that were being updated, only. @mafintosh @maxogden thoughts?

**Comment by thadguidry** [comment]
@karissa @maxogden I think `import` should be treated as an additive (AND) operation always.  And leave `update` as you suggest, to expect a list of rows that need to be updated (XOR).

**Comment by ingmars** [comment]
@maxogden , your suggestion does not solve the problem of how to delete rows from dat. I really wonder: How do people use dat in practice when there's no way to ever remove entries from data sets? For me, that is unfortunately a showstopper, no matter how well-done dat looks otherwise.

@karissa , your suggestion looks perfect to me. Have import make sure the contents in dat are the same as the contents in the CSV file you're importing after you executed the command. That operation would mean adding new entries for lines in CSV that weren't in dat before and removing lines when an entry in dat doesn't correspond to a line in the CSV file to be imported.

Of course that would break backwards compatibility. If that is a large concern, I would opt for another kind of import command that does just that.

Also, either way, I think there should be a command for selectively removing entries from the dat repository.

**Comment by maxogden** [comment]
@ingmars thanks for the feedback. I think the idea here is to have a set of commands to effectively do two-way sync between a dataset in dat and an external file.

So for example, if you had a file `people.csv`, and you did `dat import --dataset=people people.csv --key-name`, it would import all rows. If you then edited `people.csv` (e.g. with Excel) and wanted your dat to get updated to reflect the changes you made, it would be convenient to have a way to tell dat to not only import new things things from a file, but to also delete things that aren't present in a file.

We have talked previously about using `dat add` for a sort of higher level import action. The use case we're discussing here reminds me of Git, where you stage incremental changes to files using `git add`. I could see `dat add file.csv` working as described above, meaning `dat import` would only create rows whereas `dat add` would be able to create, update or delete rows. The expectation of `dat add` would be that the file you are adding is a full copy of your dataset (since if you `dat add` something and a row is not present dat will delete it in this new proposed 'mode').

I think this use case is very valid though, I think it makes sense that you would have a 1:1 relationship between a table (e.g. a CSV file or maybe an external database table) and a dataset in a dat repository, and you would want to be able to effectively sync them.

We have also been discussing how to implement deletes. This helps address that, but there might also be a need for `dat delete` to delete a specific row (or perhaps a range of rows e.g. `dat delete f*` to delete all keys starting with `f`), `dat undo` to undo the last action, and `dat clean` to do a sort of garbage collection that reclaims disk space of recently deleted items.

**Comment by karissa** [comment]
+1 on `dat add`! I had a shower thought about that yesterday. `dat delete` exists in the primitive https://github.com/maxogden/dat/blob/master/bin/delete.js. I like the idea of having regex in the key, too.

**Comment by sorrell** [comment]
@maxogden @karissa I, too, love the idea of `dat add`.  That would be a perfect solution, and the Git analogy is right on.

The specific use case I've been eyeing Dat for would utilize this functionality.  This use case is where each data source essentially creates a flat file dump of their database on a monthly basis.  Some records are CUD (is that palatable - CRUD without the R? :), and thus only the deltas need to be passed back upstream.

**Comment by timwis** [comment]
Interesting..so to confirm, at the moment there is no way to delete rows in dat? More specifically, for `dat diff` to tell you which rows were deleted as it currently tells you which rows were added/changed?

**Comment by karissa** [comment]
To delete rows right now, you'd have to remove the rest of the row so that it turns into a 'put' of null, but I know that's not a good solution. We are doing some rearchitecting of the system right now so we haven't quite made this super easy yet.

**Comment by ingmars** [comment]
Just out of curiosity: Do you plan to include the architectural changes concerning deletion of rows to be included in the upcoming dat 1.0? I believe that would be a crucial feature to include before any major version - otherwise it gets harder to include it later on due to backwards compatibility constraints etc.

**Comment by karissa** [comment]
After a whole year of feedback from the community, we recently published a new version of dat... and it makes this issue obsolete. Would you mind trying out the new dat with `npm install -g dat`? You can read about the new dat [announcement on the website](http://dat-data.com/blog/2016-02-01-dat-1) and [how it works in the docs](https://github.com/datproject/docs/blob/master/how-dat-works.md).

**Comment by ingmars** [comment]
Thanks for the pointer at the new version. As I understand it, the focus of dat changed in the latest version. While the old version appeared to me like a "Git for data", the new version seems to be more like a "Torrent for data". Since the latter is not interesting for the project I'm involved in and for which we were evaluating dat, we will refrain from using it and therefore I probably won't find the time to dig deeper into analysing whether our problem is solved by the new version. Thanks anyway for your efforts!

**Comment by timwis** [comment]
@ingmars you may want to keep an eye on [dat jawn](https://github.com/cfabrigadephiladelphia/jawn) for tabular data support

Also, props to the dat team for going where the research and revision takes them, however difficult the decisions.
