### ISSUE TITLE
JSON-LD and keys

### ISSUE THREAD

**Issue by pietercolpaert** [maxogden/dat#383]
A JSON-LD object looks something like this;
```json
{
  "@context": "http://json-ld.org/contexts/person.jsonld",
  "@id": "http://dbpedia.org/resource/John_Lennon",
  "name": "John Lennon",
  "born": "1940-10-09",
  "spouse": "http://dbpedia.org/resource/Cynthia_Lennon"
}
```
Every object has an `@id`. This `@id` is a persistent identifier for that object.

A great feature for the Linked Data community would be that `dat` automatically detects json-ld and uses the `@id` as a key to store the data by, by default.

I'm willing to implement this myself. Yet:
 * Is this a feature that would get into the main branch if it's pull requested?
 * Any pointers on how to implement this properly in the codebase of dat?

**Comment by karissa** [comment]
Hey, thanks for opening this PR. I think this is a great suggestion, and Linked Data is super important!

I'm hesitant to put any specific standards into dat, because then we'd have to support all of them. If people wanted to use `@id` as the key they could do `--key=@id`. Is there a reason why the `-k @id` interface isn't serving well? Too much? Often forgotten?

At one point, we were thinking about putting a `dat add` function that would be a little more 'magic' to walk one through a data import. Here, we could imagine a series of prompts -- one of them could try to auto-detect the unique key and ask you which column based upon that. I can imagine these kinds of higher-level features going into that.

**Comment by pietercolpaert** [comment]
Hi @karissa - Thank you for your reply. I like the higher-level idea of `dat add` and indeed, this suggestion was made because it's often forgotten.

Is this already suggested in a different issue? Or shall we proceed with closing this issue and open a new feature request for `dat add`?

**Comment by karissa** [comment]
We don't have an issue for `dat add` yet, but I will make one. We can leave this open and I'll reference it in that after I chat with the other two on the team

**Comment by karissa** [comment]
Thanks a bunch!

**Comment by karissa** [comment]
Thanks for trying out dat beta and submitting an issue. After a whole year of feedback from the community, we recently published a new version of dat... and it makes this issue obsolete. Would you mind trying out the new dat with `npm install -g dat`? You can read about the new dat [announcement on the website](http://dat-data.com/blog/2016-02-01-dat-1) and [how it works in the docs](https://github.com/datproject/docs/blob/master/how-dat-works.md).

**Comment by pietercolpaert** [comment]
Was this json-ld issue implemented in the end then?
