### ISSUE TITLE
Where would dat fit in to sharing open data in an enterprise?

### ISSUE THREAD

**Issue by timwis** [maxogden/dat#400]
Hey guys, I had a brief chat with @waldoj yesterday at Transparency Camp and I wanted to follow up about dat, as I'm about 72% sure it's key to the kind of data management we're after in the @CityOfPhiladelphia. But there's also a good chance I'm completely misunderstanding it, and I hoped you could tell me whether that's the case. (I was going to email this but I thought a GH issue may be more appropriate as I imagine we're not the only ones in this situation.)

We get data from agencies in a variety of ways: a delimited file emailed to us or put on an SFTP server, pushed manually into a database table in our central GIS database, and sometimes by pulling it ourselves from the transactional systems. These almost always require a set of transformations be applied to them to make them "shareable" (though sometimes they're done by the agency before being sent to us). Once we have the shareable version of the data, we want to make it available to (1) all agencies via our central database (so they can do joins and such), (2) the public as an API, various download formats, and visualizations (currently achieved through our Socrata + OpenDataPhilly setup), and (3) other destinations such as ArcGIS Online, data marts when they pop up, etc. It would also be great if users could see what the data looked like on a certain date (ie. with property ownership).

It feels like dat would be key in enabling this, but I'm trying to wrap my head around which piece it would fit into. It seems like it's the "L" of the ETL acronym (primarily since it can transmit deltas even after a truncate & load), and perhaps that will be more clear once CKAN/Socrata/AGOL and database connectors are built, but it's also unclear how the triggering would work, and how one might explore the history of a dataset outside of the command line.

Am I on the right track here or does dat solve a totally different problem and I'm misunderstanding it?

**Comment by karissa** [comment]
Hey @timwis, thanks for coming in.. that's a great question. I've been interested in writing up a document exactly related to this, and you're giving me an extra push! 

Dat is great at syncing and sharing data, and although we've focused on scientific use cases, it can work really well for what you're asking. You're right that it does well in the 'load step', although we are actively working on the 'extract' and 'transform' pieces. Right now, in the beta phase, I'd recommend it for (2) "as an API, various download formats, and visualizations." We'd love to help you get set up, too, if you need help. 

Here is an example that we've employed at CA Civic Data Coalition: https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/calaccess_raw/management/commands/loadcalaccessrawfile.py#L54

They have a routine that extracts the data, cleans it, and then loads it into a SQL database. This addition also inserts it into a dat data store, where each SQL table is analogous to a Dat dataset. Every time the data is loaded, it provides a `key`, which is some sort of unique identifying column. This helps dat know which data is being updated and what data is new. CA Civic Data uses karissa/datpy, but we also have ropensci/rdat if your load routine is using R.

You can then supply a dat endpoint, with `dat serve`, where other people can `dat clone`. When you run your ETL process again, dat will know which data is new, so when people `dat pull`, they will only download the newest data, and they will know exactly what changed. 

It might be useful for your transformation process, so you know what data changed each time you run the process. If the data doesn't look good, you can always rollback with `dat checkout <version>`. 

I hope this helps. If you'd like to get on a call, I'd love to walk you through the steps and answer questions. I know that we'd also love to have a dat extension in CKAN, (have talked to @waldoj about this). If that happens, you won't even have to worry about setting up dat endpoints yourself. With the extension, CKAN would create the endpoints, import the data into a dat, and people could download them by using a `.dat` extension instead of `.csv` at the end of the file URL. This would also make it easy for your load process to programmatically push data of any size to your CKAN instance.

Let me know if this helps!

**Comment by timwis** [comment]
That's great, @karissa, thank you. I'd love to take you up on that call!

**Comment by jqnatividad** [comment]
+1

**Comment by karissa** [comment]
After a whole year of feedback from the community, we recently published a new version of dat. Would you mind trying out the new dat with `npm install -g dat`? You can read about the new dat [announcement on the website](http://dat-data.com/blog/2016-02-01-dat-1) and [how it works in the docs](https://github.com/datproject/docs/blob/master/how-dat-works.md). 

We should get on a new call sometime (or come visit!) to try dat out with your use case. I think there are some things we can do to make it work really well with what you've got, as far as what I remember from our last call.

**Comment by timwis** [comment]
Hey @karissa thanks for following up. A fellow named Matt actually caught me at a meetup here in Philly and mentioned you guys dropped support for tabular data in the new version and he was looking for folks to help support it. I was then under the impression our use case was a no-go. But if you're saying it would work with the binary support, I'm certainly interested in hearing more (trying to fathom it).

**Comment by Analect** [comment]
@karissa @timwis ... I'm interested as to whether the vision articulated above (https://github.com/maxogden/dat/issues/400#issuecomment-139915170) was ever realised ... I know that [jawn](https://github.com/CfABrigadePhiladelphia/jawn) spawned out of dat moving away from the tabular-data model, but there doesn't appear to be much activity there.  @karissa, how would the new dat work with the use-case described by @timwis.  ... and are you aware of any working demo of how dat-manager might work with CKAN, as articulated [here](https://github.com/ckan/ideas-and-roadmap/issues/168#issuecomment-181511359).  Thanks.
